t3: 1.0
#####################################
# 対象言語
#####################################
languages:
  - ja_JP
#####################################
# カスタム機能定義
#####################################
info:
  name: aws-cwl
  customPackage: com.epion_t3.aws.cwl
  summary:
    - lang: ja_JP
      contents: "AWSのCloudWatchLogsへのアクセスを行う機能を提供します。"
  description:
    - lang: ja_JP
      contents: "AmazonWebService（AWS）のCloudWatchLogs（CWL）への各種アクセスを行う機能を提供します。エビデンスの取得などに利用できるGetLogStream、GetLogEventsを代表とした機能です。"
#####################################
# コマンド定義
#####################################
commands:
  ##########################
  # AwsCwlGetLogStream
  ##########################
  - id: AwsCwlGetLogStream
    evidenceCommand: true
    summary:
      - lang: ja_JP
        contents: "LogStreamを取得します。"
    testItem:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "LogGroup「${logGroupName}」からLogStreamを取得します。"
    function:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "指定されたLogGroupからLogStreamを取得します。"
      - order: 2
        summary:
          - lang: ja_JP
            contents: "logStreamNamePrefix、limit、orderBy、descendingによる取得制御が行えます。"
      - order: 3
        summary:
          - lang: ja_JP
            contents: "取得したLogStreamの一覧は、JSON形式のエビデンスとして保存します。"
      - order: 5
        summary:
          - lang: ja_JP
            contents: "エビデンスファイル名は、「実行ID ＋ logStreams.json」となります。"
    structure:
      - order: 1
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドのID
      - order: 2
        name: command
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 「AwsCwlGetLogStream」固定
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの概要（任意）
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの詳細（任意）
      - order: 6
        name: logGroupName
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "対象とするLogGroupの名前を指定します。"
      - order: 7
        name: logStreamNamePrefix
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "対象とするLogStreamの接頭辞を指定します。"
      - order: 8
        name: limit
        required: false
        type: number
        summary:
          - lang: ja_JP
            contents: "取得するLogStreamの上限件数を指定します。"
      - order: 9
        name: orderBy
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "結果のソート方法を「LogStreamName」、「LastEventTime」のいずれかを指定します。いずれかの文字列の完全一致でなければなりません。"
      - order: 10
        name: descending
        required: false
        type: boolean
        summary:
          - lang: ja_JP
            contents: "結果のソートを降順にするかどうかのフラグです。"
  ##########################
  # AwsCwlGetLogEvents
  ##########################
  - id: AwsCwlGetLogEvents
    evidenceCommand: true
    summary:
      - lang: ja_JP
        contents: "Logイベント（ログそのもの）を取得します。"
    testItem:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "LogGroup「${logGroupName}」の「${logStreamName}」からLogイベントを取得します。"
    function:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "指定されたLogGroup、LogStreamからLogイベント（ログそのもの）を取得します。"
      - order: 2
        summary:
          - lang: ja_JP
            contents: "limit、startTime、endTimeによる取得制御が行えます。"
      - order: 3
        summary:
          - lang: ja_JP
            contents: "取得したログの一覧は、JSON形式のエビデンスとして保存します。"
      - order: 5
        summary:
          - lang: ja_JP
            contents: "エビデンスファイル名は、「実行ID ＋ logEvents.json」となります。"
    structure:
      - order: 1
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドのID
      - order: 2
        name: command
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 「AwsCwlGetLogEvents」固定
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの概要（任意）
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの詳細（任意）
      - order: 6
        name: logGroupName
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "対象とするLogGroupの名前を指定します。"
      - order: 7
        name: logStreamName
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "対象とするLogStreamの接頭辞を指定します。"
      - order: 8
        name: limit
        required: false
        type: number
        summary:
          - lang: ja_JP
            contents: "取得するLogStreamの上限件数を指定します。"
      - order: 9
        name: startTime
        required: false
        type: number
        summary:
          - lang: ja_JP
            contents: "イベントの開始時間を指定します。エポックミリ秒で指定します。"
      - order: 10
        name: endTime
        required: false
        type: number
        summary:
          - lang: ja_JP
            contents: "イベントの終了時間を指定します。エポックミリ秒で指定します。"
      - order: 11
        name: startFromHead
        required: false
        type: boolean
        summary:
          - lang: ja_JP
            contents: "イベントの開始を先頭から出力するかのフラグです。デフォルトはfalseです。"
#####################################
# メッセージ定義
#####################################
messages:
  - id: com.epion_t3.aws.cwl.err.9001
    message:
      - lang: ja_JP
        contents: "CloudWatchLogsのLogStreamの取得に失敗しました。LogGroup:{0}"
  - id: com.epion_t3.aws.cwl.err.9002
    message:
      - lang: ja_JP
        contents: "CloudWatchLogsのLogEventの取得に失敗しました。LogGroup:{0}, LogStream:{1}"