t3: 1.0
#####################################
# 対象言語
#####################################
languages:
  - ja_JP
#####################################
# カスタム機能定義
#####################################
info:
  name: aws-cwl
  customPackage: com.epion_t3.aws.cwl
  summary:
    - lang: ja_JP
      contents: "AWSのCloudWatchLogsへのアクセスを行う機能を提供します。"
  description:
    - lang: ja_JP
      contents: "AmazonWebService（AWS）のCloudWatchLogs（CWL）への各種アクセスを行う機能を提供します。エビデンスの取得などに利用できるGetLogStream、GetLogEventsを代表とした機能です。"
#####################################
# コマンド定義
#####################################
commands:
  ##########################
  # AwsCwlGetLogStream
  ##########################
  - id: AwsCwlGetLogStream
    evidenceCommand: true
    summary:
      - lang: ja_JP
        contents: "LogStreamを取得します。"
    testItem:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "LogGroup「${logGroupName}」からLogStreamを取得します。"
    function:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "指定されたLogGroupからLogStreamを取得します。"
      - order: 2
        summary:
          - lang: ja_JP
            contents: "logStreamNamePrefix、limit、orderBy、descendingによる取得制御が行えます。"
      - order: 3
        summary:
          - lang: ja_JP
            contents: "取得したLogStreamの一覧は、JSON形式のエビデンスとして保存します。"
      - order: 5
        summary:
          - lang: ja_JP
            contents: "エビデンスファイル名は、「実行ID ＋ logStreams.json」となります。"
    structure:
      - order: 1
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドのID
      - order: 2
        name: command
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 「AwsCwlGetLogStream」固定
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの概要（任意）
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの詳細（任意）
      - order: 5
        name: credentialsConfigRef
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "資格設定の参照"
      - order: 6
        name: sdkHttpClientConfigRef
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "HTTPクライアント設定の参照"
      - order: 7
        name: logGroupName
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "対象とするLogGroupの名前を指定します。"
      - order: 8
        name: logStreamNamePrefix
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "対象とするLogStreamの接頭辞を指定します。"
      - order: 9
        name: limit
        required: false
        type: number
        summary:
          - lang: ja_JP
            contents: "取得するLogStreamの上限件数を指定します。"
      - order: 10
        name: orderBy
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "結果のソート方法を「LogStreamName」、「LastEventTime」のいずれかを指定します。いずれかの文字列の完全一致でなければなりません。"
      - order: 11
        name: descending
        required: false
        type: boolean
        summary:
          - lang: ja_JP
            contents: "結果のソートを降順にするかどうかのフラグです。"
  ##########################
  # AwsCwlGetLogEvents
  ##########################
  - id: AwsCwlGetLogEvents
    evidenceCommand: true
    summary:
      - lang: ja_JP
        contents: "Logイベント（ログそのもの）を取得します。"
    testItem:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "LogGroup「${logGroupName}」の「${logStreamName}」からLogイベントを取得します。"
    function:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "指定されたLogGroup、LogStreamからLogイベント（ログそのもの）を取得します。"
      - order: 2
        summary:
          - lang: ja_JP
            contents: "limit、startTime、endTimeによる取得制御が行えます。"
      - order: 3
        summary:
          - lang: ja_JP
            contents: "取得したログの一覧は、JSON形式のエビデンスとして保存します。"
      - order: 5
        summary:
          - lang: ja_JP
            contents: "エビデンスファイル名は、「実行ID ＋ logEvents.json」となります。"
    structure:
      - order: 1
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドのID
      - order: 2
        name: command
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 「AwsCwlGetLogEvents」固定
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの概要（任意）
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの詳細（任意）
      - order: 5
        name: credentialsConfigRef
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "資格設定の参照"
      - order: 6
        name: sdkHttpClientConfigRef
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "HTTPクライアント設定の参照"
      - order: 7
        name: logGroupName
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "対象とするLogGroupの名前を指定します。"
      - order: 8
        name: logStreamName
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "対象とするLogStreamの接頭辞を指定します。"
      - order: 9
        name: limit
        required: false
        type: number
        summary:
          - lang: ja_JP
            contents: "取得するLogStreamの上限件数を指定します。この数より多いLogStreamが存在する場合でも指定された値までしか取得しません。"
      - order: 10
        name: startTime
        required: false
        type: number
        summary:
          - lang: ja_JP
            contents: "イベントの開始時間を指定します。エポックミリ秒で指定します。"
      - order: 11
        name: endTime
        required: false
        type: number
        summary:
          - lang: ja_JP
            contents: "イベントの終了時間を指定します。エポックミリ秒で指定します。"
      - order: 12
        name: startFromHead
        required: false
        type: boolean
        summary:
          - lang: ja_JP
            contents: "イベントの開始を先頭から出力するかのフラグです。デフォルトはfalseです。"
  ##########################
  # AwsCwlGetLogStreamEvents
  ##########################
  - id: AwsCwlGetLogStreamEvents
    evidenceCommand: true
    assertCommand: false
    summary:
      - lang: ja_JP
        contents: "指定されたLogGroupの最終LogStreamのLogイベントを取得します。"
    testItem:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "LogGroup「${logGroupName}」の最終LogStreamからLogイベントを取得します。"
    function:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "指定されたLogGroupの最終LogStreamのLogイベントを取得します。"
      - order: 2
        summary:
          - lang: ja_JP
            contents: "logStreamNamePrefix、limit、orderBy、descendingによるLogStream取得制御が行えます。"
      - order: 3
        summary:
          - lang: ja_JP
            contents: "eventsLimit、startTime、endTimeによるLogイベント取得制御が行えます。"
      - order: 4
        summary:
          - lang: ja_JP
            contents: "取得したログの一覧は、JSON形式のエビデンスとして保存します。"
      - order: 5
        summary:
          - lang: ja_JP
            contents: "エビデンスファイル名は、「実行ID ＋ logEvents.json」となります。"
    structure:
      - order: 1
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドのID
      - order: 2
        name: command
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 「AwsCwlGetLogStreamEvents」固定
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの概要（任意）
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの詳細（任意）
      - order: 5
        name: credentialsConfigRef
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "資格設定の参照"
      - order: 6
        name: sdkHttpClientConfigRef
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "HTTPクライアント設定の参照"
      - order: 7
        name: logGroupName
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "対象とするLogGroupの名前を指定します。"
      - order: 8
        name: logStreamNamePrefix
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "対象とするLogStreamの接頭辞を指定します。"
      - order: 9
        name: streamLimit
        required: false
        type: number
        summary:
          - lang: ja_JP
            contents: "LogStreamの件数の上限を設定します。デフォルトは1です。この数より多いLogStreamが存在する場合でも指定された値までしか取得しません。"
      - order: 10
        name: orderBy
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "結果のソート方法を「LogStreamName」、「LastEventTime」のいずれかを指定します。いずれかの文字列の完全一致でなければなりません。"
      - order: 11
        name: descending
        required: false
        type: boolean
        summary:
          - lang: ja_JP
            contents: "結果のソートを降順にするかどうかのフラグです。"
      - order: 12
        name: eventLimit
        required: false
        type: number
        summary:
          - lang: ja_JP
            contents: "取得するLogイベントの上限件数を指定します。この数より多いLogイベントが存在する場合でも指定された値までしか取得しません。"
      - order: 13
        name: startTime
        required: false
        type: number
        summary:
          - lang: ja_JP
            contents: "イベントの開始時間を指定します。エポックミリ秒で指定します。"
      - order: 14
        name: endTime
        required: false
        type: number
        summary:
          - lang: ja_JP
            contents: "イベントの終了時間を指定します。エポックミリ秒で指定します。"
      - order: 15
        name: startFromHead
        required: false
        type: boolean
        summary:
          - lang: ja_JP
            contents: "イベントの開始を先頭から出力するかのフラグです。デフォルトはfalseです。"
  ##########################
  # AwsCwlAssertLogEvents
  ##########################
  - id: AwsCwlAssertLogEvents
    evidenceCommand: false
    assertCommand: true
    summary:
      - lang: ja_JP
        contents: "LogEventのアサートを行います。"
    testItem:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "FlowId「${actualFlowId}」で取得したエビデンスからLogEventの確認を行います。"
    function:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "指定されたFlowIdのエビデンスを元にLogEventのアサートを行います。"
      - order: 2
        summary:
          - lang: ja_JP
            contents: "エビデンスは、本カスタム機能で取得・保存されたものにのみ対応しています。"
      - order: 3
        summary:
          - lang: ja_JP
            contents: "確認は文字列で行いますが、正規表現によるものと、完全一致によるものの2択から選べます。"
    structure:
      - order: 1
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドのID
      - order: 2
        name: command
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 「AwsCwlAssertLogEvents」固定
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの概要（任意）
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの詳細（任意）
      - order: 6
        name: actualFlowId
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "結果値をエビデンスとして取得したFlowIdを指定します。"
      - order: 7
        name: json
        required: false
        type: boolean
        summary:
          - lang: ja_JP
            contents: "対象のメッセージがJSONであるかを指定します。デフォルトはfalse＝JSONでない。となります。"
      - order: 8
        name: targetJsonPath
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "jsonが「true」の場合に、アサート対象を取得するためのJSONPathを指定します。"
      - order: 9
        name: expected
        required: false
        type: array
        summary:
          - lang: ja_JP
            contents: "期待値リストです。"
        propertye:
          - order: 1
            name: pattern
            required: true
            type: string
            summary:
              - lang: ja_JP
                contents: "比較するパターンです。正規表現もしくは完全一致を確認する文字列を指定します。"
          - order: 2
            name: regexp
            required: true
            type: boolean
            summary:
              - lang: ja_JP
                contents: "patternが正規表現である場合には、「true」を指定します。"
#####################################
# メッセージ定義
#####################################
messages:
  - id: com.epion_t3.aws.cwl.err.9001
    message:
      - lang: ja_JP
        contents: "CloudWatchLogsのLogStreamの取得に失敗しました。LogGroup:{0}"
  - id: com.epion_t3.aws.cwl.err.9002
    message:
      - lang: ja_JP
        contents: "CloudWatchLogsのLogEventの取得に失敗しました。LogGroup:{0}, LogStream:{1}"
  - id: com.epion_t3.aws.cwl.err.9003
    message:
      - lang: ja_JP
        contents: "合致するLogStreamが1件も見つかりません。LogGroup:{0}"
  - id: com.epion_t3.aws.cwl.err.9004
    message:
      - lang: ja_JP
        contents: "メッセージのJSON解析に失敗しました。JSON形式でない場合は、json指定をfalseにしてください。"
  - id: com.epion_t3.aws.cwl.err.9005
    message:
      - lang: ja_JP
        contents: "結果値が見つかりません.　パス:{0}, FlowId:{1}"